image: node:18

pipelines:
  custom:
    trabalho-final:
      - step:
          name: "Executando testes do Trabalho Final"
          caches:
            - node
          script:
            #- npm install -g yarn (o Yarn já está instalado na imagem node:18)
            - yarn
            - yarn run test-trabalho